import { consumeNonceResult } from '@/lib/extension-oauth-nonce'
import { NextRequest, NextResponse } from 'next/server'

function getCorsHeaders(req: NextRequest): Headers {
    const headers = new Headers()
    const origin = req.headers.get('origin')
    const isExtensionOrigin =
        origin?.startsWith('chrome-extension://') ||
        origin?.startsWith('moz-extension://') ||
        origin?.startsWith('safari-web-extension://')

    if (isExtensionOrigin && origin) {
        headers.set('Access-Control-Allow-Origin', origin)
        headers.set('Access-Control-Allow-Methods', 'GET, OPTIONS')
        headers.set('Access-Control-Allow-Headers', 'Content-Type')
    }

    return headers
}

export async function OPTIONS(req: NextRequest) {
    return new NextResponse(null, { status: 204, headers: getCorsHeaders(req) })
}

/**
 * Polled by the extension popup (Safari path) to retrieve the OAuth result that
 * was stashed by /api/extension/oauth/redirect after server-side completion.
 *
 * Returns:
 *   200 { token, username, image } once available — entry is consumed (one-shot)
 *   204 (No Content) while the user is still completing OAuth
 *
 * The nonce is generated by the popup, sent to /authorize, embedded in the
 * signed state, and threaded through the OAuth provider so the result lands
 * here keyed by the same value.
 */
export async function GET(req: NextRequest) {
    const corsHeaders = getCorsHeaders(req)
    const nonce = req.nextUrl.searchParams.get('nonce')

    if (!nonce || nonce.length < 16 || nonce.length > 128) {
        return NextResponse.json(
            { error: 'Missing or invalid nonce' },
            { status: 400, headers: corsHeaders },
        )
    }

    const entry = consumeNonceResult(nonce)
    if (!entry) {
        return new NextResponse(null, { status: 204, headers: corsHeaders })
    }

    if (!entry.token) {
        // Sentinel for sign-in failure — popup should surface a generic error.
        return NextResponse.json(
            { error: 'OAuth sign-in failed' },
            { status: 400, headers: corsHeaders },
        )
    }

    return NextResponse.json(
        {
            token: entry.token,
            username: entry.username,
            image: entry.image,
        },
        { headers: corsHeaders },
    )
}
